// completions.ts — print shell completion scripts for `convoy`.
//
// convoy dispatches subcommands via a hand-written `switch` in cli.ts and its `--help` is prose, so
// there is no machine-readable surface to derive completions from directly. src/command-table.ts is
// that surface: this module renders fish / bash / zsh from that ONE tree, so the three scripts cannot
// drift apart — and, because argv dispatch derives its `unknownFlag` allow-lists from the same tree,
// they cannot drift from what the CLI actually accepts either.
//
// Two things the generators care about beyond the flag names:
//
//   1. Path completion. `--dir`, `--repo`, `--persona`, `--config-dir`, `--bin`, `--megarepo` and the
//      `pretrust <dir>` / `init [dir]` positionals take filesystem paths. A flag marked `takesPath`
//      gets real file completion instead of an opaque "needs a value" (fish `-rF`, not `-x`).
//   2. Dynamic values. Networks and agent identities have no static list — they are dirs under
//      convoy's home and `*.toml` files in the network's catalog. `dynamic:` emits the per-shell
//      idiom that reads them at completion time, honoring XDG_STATE_HOME / CONVOY_NETWORK / ST_ROOT
//      exactly as src/paths.ts does.

import { COMMANDS, HELP_FLAG, TOP_LEVEL_FLAGS, type CommandSpec, type FlagSpec } from "./command-table.ts";

/** Flags offered under every subcommand: its own, plus the universally honored `--help`. */
function flagsOf(c: CommandSpec): readonly FlagSpec[] {
  return [...(c.flags ?? []), HELP_FLAG];
}

// ─── fish ────────────────────────────────────────────────────────────────────

/** Single-quote for fish (fish only special-cases `'` and `\`). */
function q(s: string): string {
  return `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function fishScript(): string {
  const out: string[] = [];
  out.push("# fish completions for convoy — generated by `convoy completions fish`.");
  out.push("# Do not edit: regenerate instead. Source of truth: src/command-table.ts.");
  out.push("");
  // Network/identity discovery mirrors src/paths.ts so the completions and the CLI resolve the same dirs.
  out.push("function __convoy_home");
  out.push("    if set -q XDG_STATE_HOME");
  out.push('        echo "$XDG_STATE_HOME/convoy"');
  out.push("    else");
  out.push('        echo "$HOME/.local/state/convoy"');
  out.push("    end");
  out.push("end");
  out.push("");
  out.push("function __convoy_networks");
  out.push("    set -l home (__convoy_home)");
  out.push('    if test -d "$home"');
  out.push('        for d in "$home"/*/');
  out.push('            basename "$d"');
  out.push("        end");
  out.push("    end");
  out.push("end");
  out.push("");
  out.push("# The network in play: CONVOY_NETWORK, else ST_ROOT (which points at <net>/smalltalk), else the default.");
  out.push("function __convoy_network_dir");
  out.push("    if set -q CONVOY_NETWORK");
  out.push('        echo "$CONVOY_NETWORK"');
  out.push("    else if set -q ST_ROOT");
  out.push('        if test (basename "$ST_ROOT") = smalltalk');
  out.push('            dirname "$ST_ROOT"');
  out.push("        else");
  out.push('            echo "$ST_ROOT"');
  out.push("        end");
  out.push("    else");
  out.push('        echo (__convoy_home)"/default"');
  out.push("    end");
  out.push("end");
  out.push("");
  out.push("function __convoy_identities");
  out.push("    set -l catalog (__convoy_network_dir)/catalog");
  out.push('    if test -d "$catalog"');
  out.push('        for f in "$catalog"/*.toml');
  out.push('            test -f "$f"; and basename "$f" .toml');
  out.push("        end");
  out.push("    end");
  out.push("end");
  out.push("");
  out.push("function __convoy_needs_command");
  out.push("    set -l cmd (commandline -opc)");
  out.push("    test (count $cmd) -eq 1");
  out.push("end");
  out.push("");
  out.push("function __convoy_using_command");
  out.push("    set -l cmd (commandline -opc)");
  out.push('    test (count $cmd) -ge 2; and test "$cmd[2]" = "$argv[1]"');
  out.push("end");
  out.push("");
  // No bare file completion: every path position opts back in with -F below.
  out.push("complete -c convoy -f");
  out.push("");
  out.push("# ── Top level ─────────────────────────────────────────────────────────");
  for (const f of TOP_LEVEL_FLAGS) {
    out.push(`complete -c convoy -n __convoy_needs_command -l ${f.name} -d ${q(f.desc)}`);
  }
  out.push(`complete -c convoy -n __convoy_needs_command -s h -d ${q(HELP_FLAG.desc)}`);
  for (const c of COMMANDS) {
    out.push(`complete -c convoy -n __convoy_needs_command -a ${c.name} -d ${q(c.desc)}`);
  }
  out.push("");
  out.push("# ── Subcommands ───────────────────────────────────────────────────────");
  for (const c of COMMANDS) {
    const guard = q(`__convoy_using_command ${c.name}`);
    for (const f of flagsOf(c)) {
      if (f.kind === "bool") {
        out.push(`complete -c convoy -n ${guard} -l ${f.name} -d ${q(f.desc)}`);
      } else if (f.takesPath) {
        // -r (requires an argument) + -F (offer real files) — the fix for `-x` on a path flag.
        out.push(`complete -c convoy -n ${guard} -l ${f.name} -r -F -d ${q(f.desc)}`);
      } else if (f.values) {
        out.push(`complete -c convoy -n ${guard} -l ${f.name} -x -a ${q(f.values.join(" "))} -d ${q(f.desc)}`);
      } else {
        out.push(`complete -c convoy -n ${guard} -l ${f.name} -x -d ${q(f.desc)}`);
      }
    }
    out.push(`complete -c convoy -n ${guard} -s h -d ${q(HELP_FLAG.desc)}`);
    const p = c.positional;
    if (p === undefined) continue;
    if (p.dynamic === "networks") out.push(`complete -c convoy -n ${guard} -a '(__convoy_networks)' -d ${q(p.desc)}`);
    if (p.dynamic === "identities") out.push(`complete -c convoy -n ${guard} -a '(__convoy_identities)' -d ${q(p.desc)}`);
    if (p.values) out.push(`complete -c convoy -n ${guard} -a ${q(p.values.join(" "))} -d ${q(p.desc)}`);
    if (p.takesPath) out.push(`complete -c convoy -n ${guard} -F`);
  }
  return out.join("\n") + "\n";
}

// ─── bash ────────────────────────────────────────────────────────────────────
//
// A flat completer over the same tree. Behavioral parity with fish is a non-goal (fish is the rich
// one); this gives subcommand + flag + dynamic network/identity completion, and falls back to bash's
// own file completion wherever a path is expected.

function bashScript(): string {
  const lines: string[] = [];
  lines.push("# bash completion for convoy — generated by `convoy completions bash`.");
  lines.push("# Do not edit: regenerate instead. Source of truth: src/command-table.ts.");
  lines.push("_convoy_home() {");
  lines.push('  echo "${XDG_STATE_HOME:-$HOME/.local/state}/convoy"');
  lines.push("}");
  lines.push("_convoy_networks() {");
  lines.push('  local home; home="$(_convoy_home)"');
  lines.push('  [[ -d "${home}" ]] || return 0');
  lines.push('  local d; for d in "${home}"/*/; do [[ -d "${d}" ]] && basename "${d}"; done');
  lines.push("}");
  lines.push("_convoy_network_dir() {");
  lines.push('  if [[ -n "${CONVOY_NETWORK:-}" ]]; then echo "${CONVOY_NETWORK}"; return; fi');
  lines.push('  if [[ -n "${ST_ROOT:-}" ]]; then');
  lines.push('    if [[ "$(basename "${ST_ROOT}")" == smalltalk ]]; then dirname "${ST_ROOT}"; else echo "${ST_ROOT}"; fi');
  lines.push("    return");
  lines.push("  fi");
  lines.push('  echo "$(_convoy_home)/default"');
  lines.push("}");
  lines.push("_convoy_identities() {");
  lines.push('  local catalog; catalog="$(_convoy_network_dir)/catalog"');
  lines.push('  [[ -d "${catalog}" ]] || return 0');
  lines.push('  local f; for f in "${catalog}"/*.toml; do [[ -f "${f}" ]] && basename "${f}" .toml; done');
  lines.push("}");
  lines.push("_convoy() {");
  lines.push("  local cur prev");
  lines.push("  COMPREPLY=()");
  lines.push('  cur="${COMP_WORDS[COMP_CWORD]}"');
  lines.push('  prev="${COMP_WORDS[COMP_CWORD-1]}"');
  lines.push(`  local commands="${COMMANDS.map((c) => c.name).join(" ")}"`);
  lines.push("");
  lines.push("  if [[ ${COMP_CWORD} -eq 1 ]]; then");
  lines.push('    if [[ "${cur}" == -* ]]; then');
  lines.push(`      COMPREPLY=($(compgen -W "${TOP_LEVEL_FLAGS.map((f) => `--${f.name}`).join(" ")} -h" -- "\${cur}"))`);
  lines.push("    else");
  lines.push('      COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))');
  lines.push("    fi");
  lines.push("    return");
  lines.push("  fi");
  lines.push("");
  // A path-valued flag as the previous word: hand the position to bash's file completion.
  const pathFlags = [...new Set(COMMANDS.flatMap((c) => (c.flags ?? []).filter((f) => f.takesPath).map((f) => `--${f.name}`)))];
  lines.push(`  case "\${prev}" in`);
  lines.push(`    ${pathFlags.join("|")})`);
  lines.push('      COMPREPLY=($(compgen -f -- "${cur}"))');
  lines.push("      return");
  lines.push("      ;;");
  for (const f of COMMANDS.flatMap((c) => c.flags ?? []).filter((f) => f.values)) {
    lines.push(`    --${f.name})`);
    lines.push(`      COMPREPLY=($(compgen -W "${f.values!.join(" ")}" -- "\${cur}"))`);
    lines.push("      return");
    lines.push("      ;;");
  }
  lines.push("  esac");
  lines.push("");
  lines.push('  case "${COMP_WORDS[1]}" in');
  for (const c of COMMANDS) {
    const flagWords = flagsOf(c).map((f) => `--${f.name}`).join(" ");
    lines.push(`    ${c.name})`);
    lines.push('      if [[ "${cur}" == -* ]]; then');
    lines.push(`        COMPREPLY=($(compgen -W "${flagWords}" -- "\${cur}"))`);
    lines.push("      else");
    const p = c.positional;
    if (p?.dynamic === "networks") lines.push('        COMPREPLY=($(compgen -W "$(_convoy_networks)" -- "${cur}"))');
    else if (p?.dynamic === "identities") lines.push('        COMPREPLY=($(compgen -W "$(_convoy_identities)" -- "${cur}"))');
    else if (p?.values) lines.push(`        COMPREPLY=($(compgen -W "${p.values.join(" ")}" -- "\${cur}"))`);
    else if (p?.takesPath) lines.push('        COMPREPLY=($(compgen -f -- "${cur}"))');
    else lines.push("        COMPREPLY=()");
    if (p?.takesPath && p.dynamic !== undefined) {
      lines.push('        COMPREPLY+=($(compgen -f -- "${cur}"))');
    }
    lines.push("      fi");
    lines.push("      ;;");
  }
  lines.push("  esac");
  lines.push("}");
  lines.push("complete -F _convoy convoy");
  return lines.join("\n") + "\n";
}

// ─── zsh ─────────────────────────────────────────────────────────────────────

/** Escape for a zsh `_arguments` spec / `_describe` entry (`:` and `[` are structural there). */
function z(s: string): string {
  return s.replace(/[:\[\]]/g, " ");
}

function zshScript(): string {
  const lines: string[] = [];
  lines.push("#compdef convoy");
  lines.push("# zsh completion for convoy — generated by `convoy completions zsh`.");
  lines.push("# Do not edit: regenerate instead. Source of truth: src/command-table.ts.");
  lines.push("_convoy() {");
  lines.push('  local home="${XDG_STATE_HOME:-$HOME/.local/state}/convoy"');
  lines.push("");
  lines.push("  _convoy_networks() {");
  lines.push("    local -a nets");
  lines.push('    [[ -d "${home}" ]] && nets=(${home}/*(N/:t))');
  lines.push("    _describe 'network' nets");
  lines.push("  }");
  lines.push("");
  lines.push("  _convoy_identities() {");
  lines.push("    local net");
  lines.push('    if [[ -n "${CONVOY_NETWORK}" ]]; then');
  lines.push('      net="${CONVOY_NETWORK}"');
  lines.push('    elif [[ -n "${ST_ROOT}" ]]; then');
  lines.push('      if [[ "${ST_ROOT:t}" == smalltalk ]]; then net="${ST_ROOT:h}"; else net="${ST_ROOT}"; fi');
  lines.push("    else");
  lines.push('      net="${home}/default"');
  lines.push("    fi");
  lines.push("    local -a ids");
  lines.push('    [[ -d "${net}/catalog" ]] && ids=(${net}/catalog/*.toml(N:t:r))');
  lines.push("    _describe 'identity' ids");
  lines.push("  }");
  lines.push("");
  lines.push("  local -a commands");
  lines.push("  commands=(");
  for (const c of COMMANDS) lines.push(`    '${c.name}:${z(c.desc)}'`);
  lines.push("  )");
  lines.push("");
  lines.push("  _arguments -C \\");
  for (const f of TOP_LEVEL_FLAGS) lines.push(`    '--${f.name}[${z(f.desc)}]' \\`);
  lines.push("    '1:command:->command' \\");
  lines.push("    '*::arg:->args'");
  lines.push("");
  lines.push("  case $state in");
  lines.push("    command)");
  lines.push("      _describe 'command' commands");
  lines.push("      ;;");
  lines.push("    args)");
  lines.push("      case ${words[1]} in");
  for (const c of COMMANDS) {
    lines.push(`        ${c.name})`);
    const specs: string[] = [];
    for (const f of flagsOf(c)) {
      if (f.kind === "bool") specs.push(`'--${f.name}[${z(f.desc)}]'`);
      else if (f.takesPath) specs.push(`'--${f.name}[${z(f.desc)}]:path:_files'`);
      else if (f.values) specs.push(`'--${f.name}[${z(f.desc)}]:${z(f.name)}:(${f.values.join(" ")})'`);
      else specs.push(`'--${f.name}[${z(f.desc)}]:${z(f.name)}:'`);
    }
    const p = c.positional;
    if (p?.dynamic === "networks") specs.push("'*:network:_convoy_networks'");
    else if (p?.dynamic === "identities") specs.push("'*:identity:_convoy_identities'");
    else if (p?.values) specs.push(`'*:${z(p.desc)}:(${p.values.join(" ")})'`);
    else if (p?.takesPath) specs.push("'*:path:_files'");
    if (specs.length > 0) {
      lines.push("          _arguments \\");
      lines.push("            " + specs.join(" \\\n            "));
    }
    lines.push("          ;;");
  }
  lines.push("      esac");
  lines.push("      ;;");
  lines.push("  esac");
  lines.push("}");
  lines.push("");
  lines.push('_convoy "$@"');
  return lines.join("\n") + "\n";
}

// ─── Dispatch ────────────────────────────────────────────────────────────────

const GENERATORS: Record<string, () => string> = {
  bash: bashScript,
  fish: fishScript,
  zsh: zshScript,
};

const SHELLS = Object.keys(GENERATORS);

function usageText(): string {
  return (
    "usage: convoy completions <shell>\n\n" +
    "Print a shell completion script to stdout.\n\n" +
    "Shells:\n" +
    SHELLS.map((s) => `  ${s}`).join("\n") +
    "\n\nExamples:\n" +
    "  convoy completions fish > ~/.config/fish/completions/convoy.fish\n" +
    "  convoy completions bash > /etc/bash_completion.d/convoy\n" +
    '  convoy completions zsh  > "${fpath[1]}/_convoy"\n'
  );
}

/** `convoy completions <shell>` — write a completion script for `shell` to stdout. An unknown or
 *  missing shell prints usage to stderr and returns 2 (convoy's usage-error code). */
export function cmdCompletions(args: readonly string[]): number {
  const shell = args[0];
  if (shell === undefined) {
    process.stderr.write(usageText());
    return 2;
  }
  const gen = GENERATORS[shell];
  if (gen === undefined) {
    process.stderr.write(`convoy completions: unknown shell "${shell}".\n\n`);
    process.stderr.write(usageText());
    return 2;
  }
  process.stdout.write(gen());
  return 0;
}

export { SHELLS, bashScript, fishScript, zshScript };
